name: Publish pipeline

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Create Release Notes
      run: ./gradlew createReleaseNotes
    - name: Create Version File
      run: ./gradlew createVersionFile
    - name: Export version
      run: echo "PLUGIN_VERSION=$(cat build/version.md)" >> $GITHUB_ENV
    - name: Publish Gradle Plugin
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: ./gradlew -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET publishPlugins
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PLUGIN_VERSION }}
        release_name: ${{ env.PLUGIN_VERSION }}
        draft: false
        prerelease: false
        body_path: build/release-notes.md

